version: '3.8'

services:
  stumped-backend:
    container_name: stumped-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    ports:
      - "3005:3005"
    env_file:
      - backend/.env
    environment:
      - PORT=3005
      - NODE_ENV=production
    networks:
      - tunnel

networks:
  tunnel:
    external: true
    name: shared-net
